### ISSUE TITLE
json looks incorrect

### ISSUE THREAD

**Issue by codefromthecrypt** [second-state/runw#8]
I was poking at this and noticed very strange json for hydai/wasm-wasi-example:latest

The image manifest looks alright

https://index.docker.io/v2/hydai/wasm-wasi-example/manifests/latest
```json
{
  "schemaVersion": 2,
  "config": {
    "mediaType": "application/vnd.oci.image.config.v1+json",
    "digest": "sha256:0e57ad93fbcb40cf87adc028db35394a0cbc7c93839ea40d26cbdbb41be5cfc8",
    "size": 655
  },
  "layers": [
    {
      "mediaType": "application/vnd.oci.image.layer.v1.tar+gzip",
      "digest": "sha256:d32a6c4007d1e621570c435642f9fdfd425d173aecd0d047e956fe6d46dc37e1",
      "size": 362167
    }
  ]
}
```

The config looks totally wrong. The layer that has the contents is marked empty, and the CMD layer that should be marked empty is not. In fact I'm not sure why there's a CMD layer either. Definitely the content layer shouldn't be marked empty.

https://index.docker.io/v2/hydai/wasm-wasi-example/blobs/sha256:0e57ad93fbcb40cf87adc028db35394a0cbc7c93839ea40d26cbdbb41be5cfc8
```json
{
  "created": "2021-06-25T13:07:33.961015835Z",
  "architecture": "amd64",
  "os": "linux",
  "config": {
    "Env": [
      "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ],
    "Cmd": [
      "wasi_example_main.wasm"
    ],
    "Labels": {
      "io.buildah.version": "1.21.0"
    }
  },
  "rootfs": {
    "type": "layers",
    "diff_ids": [
      "sha256:8377e485d30985c1cc1809f46b80afece4eff09a0ee0247d3ae4e28d06c44900"
    ]
  },
  "history": [
    {
      "created": "2021-06-25T13:07:33.958348109Z",
      "created_by": "/bin/sh -c #(nop) ADD file:53188592204dc46c5b98cc0aac6cae818a082ca5b0c545c8e46cb87a59cd60c2 in . ",
      "empty_layer": true
    },
    {
      "created": "2021-06-25T13:07:33.975615575Z",
      "created_by": "/bin/sh -c #(nop) CMD [\"wasi_example_main.wasm\"]"
    }
  ]
}
```

I think you should make sure there is no bug in the tools being used, unless I'm missing some strange rule that empty_layer is supposed to be true on non-empty!

**Comment by hydai** [comment]
Hi @codefromthecrypt,

Thanks for indicating this issue.
I will try to figure out the `empty_layer` part. It seems like the `empty_layer` should be the CMD layer, and the ADD layer should be non-empty layer.

I used the `buildah` tool to create this image with the following dockerfile:

```Dockerfile
FROM scratch
ADD wasi_example_main.wasm .
CMD ["wasi_example_main.wasm"]
```

And use the following commands to create and push the image:

```bash
sudo buildah bud -f Dockerfile -t wasm-wasi-example
sudo buildah push --authfile ~/.docker/config.json wasm-wasi-example docker://docker.io/hydai/wasm-wasi-example:latest
```
 
`buildah` information:
```
buildah version 1.21.0 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Comment by hydai** [comment]
I just update the docker image with `docker` tool. 

After using `docker`, I can receive the following output:

```json
"docker_version": "20.10.7",
  "history": [
    {
      "created": "2021-07-01T10:45:23.8333585Z",
      "created_by": "/bin/sh -c #(nop) ADD file:603e543aa882bc3cb282c8885d8c6ab7acd0c27f7f457d818e7943cf325a8bb5 in . "
    },
    {
      "created": "2021-07-01T10:45:26.313986719Z",
      "created_by": "/bin/sh -c #(nop)  CMD [\"wasi_example_main.wasm\"]",
      "empty_layer": true
    }
  ]
```

I also updated the docker image. And my next step is to figure out why the `buildah` will generate different output. Thanks for your information.

**Comment by codefromthecrypt** [comment]
thanks!
